### PR TITLE
Added ALA directory and data files

### PR DESCRIPTION
**Pull request by nickdos**
As requested in https://github.com/VertNet/dwc-qa-manage/issues/39.

### CODE REVIEW

**Comment by ansell** [comment]
These are the processed values, not the raw data that we are collecting from data providers and giving to GBIF. (Not sure if that is an issue)

**Comment by debpaul** [comment]
Raw would be great too.

Sent from Shoe (my iPhone)

On Jul 4, 2018, at 5:49 PM, Peter Ansell <notifications@github.com<mailto:notifications@github.com>> wrote:


These are the processed values, not the raw data that we are collecting from data providers and giving to GBIF. (Not sure if that is an issue)

**Comment by nickdos** [comment]
They are actually a mixture of raw and processed values as I used any field that was indexed in SOLR. I've pasted the mapping below - key is ALA version and value is DwC term:

```
DWCMAP[basis_of_record]=basisOfRecord
DWCMAP[country_code]=countrycode
DWCMAP[country]=country
DWCMAP[month]=month
DWCMAP[year]=year
DWCMAP[establishment_means]=establishmentMeans
DWCMAP[raw_identification_qualifier]=identificationQualifier
DWCMAP[license]=license
DWCMAP[occurrence_status_s]=occurrenceStatus
DWCMAP[reproductive_condition_s]=reproductiveCondition
DWCMAP[raw_sex]=sex
DWCMAP[rank]=taxonRank
DWCMAP[type_status]=typeStatus
```

**Comment by tucotuco** [comment]
Maybe a README.md file to explain the content? In particular how to get the
raw data from the data set. This exercise is mostly to determine what one
finds in the wild.  And thanks!

**Pull request merged**
